apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
  labels:
    app: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
        - name: discountapi
          image: ngophuocloc/discountapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              value: "Server=postgres-service;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
              #còn identity server
            - name: IdentityServerSetting__IdsUrl
              value: "http://identityserver-service:80"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: NodePort
  selector:
    app: discountapi
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 31004

