apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
        - name: identityserver
          image: ngophuocloc/identityserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:
  type: NodePort
  selector:
    app: identityserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091
